FROM us-docker.pkg.dev/rocketvector/docker/baseline-spark:latest

USER root
RUN apt update -y \
    && apt install -y \
    make \
    libeigen3-dev \
    libgmp-dev \
    libgmpxx4ldbl \
    libmpfr-dev \
    libboost-dev \
    libboost-thread-dev \
    libtbb-dev \
    python3-dev \
    build-essential \
    cmake

USER spark
RUN mkdir /home/spark/PyMesh
COPY --chown=spark:spark . /home/spark/PyMesh
RUN cd /home/spark/PyMesh \
    && python setup.py clean \
    && python setup.py bdist_wheel